In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'C:\\workspaces\\전처리 데이터'

In [4]:
df = pd.read_csv('보훈대상자 평균 개인소득 2021.csv')
df.head()

,Unnamed: 0,C1_OBJ_NM,C2_NM,DT,C1_NM,UNIT_NM,ITM_NM,C2_OBJ_NM,TBL_NM
0,0,특성별,전체(경상소득),2927.6,전체,만원,보훈대상자 평균 개인소득,소득별,보훈대상자 평균 개인소득
1,1,특성별,근로소득,789.0,전체,만원,보훈대상자 평균 개인소득,소득별,보훈대상자 평균 개인소득
2,2,특성별,사업소득,349.7,전체,만원,보훈대상자 평균 개인소득,소득별,보훈대상자 평균 개인소득
3,3,특성별,재산소득,142.2,전체,만원,보훈대상자 평균 개인소득,소득별,보훈대상자 평균 개인소득
4,4,특성별,사적이전소득,94.3,전체,만원,보훈대상자 평균 개인소득,소득별,보훈대상자 평균 개인소득

In [5]:
# 불필요한 컬럼 제거
rem = ['Unnamed: 0','C1_OBJ_NM','UNIT_NM','ITM_NM','C2_OBJ_NM']

df.drop(columns = rem, inplace = True)
df

        C2_NM      DT    C1_NM         TBL_NM
0    전체(경상소득)  2927.6       전체  보훈대상자 평균 개인소득
1        근로소득   789.0       전체  보훈대상자 평균 개인소득
2        사업소득   349.7       전체  보훈대상자 평균 개인소득
3        재산소득   142.2       전체  보훈대상자 평균 개인소득
4      사적이전소득    94.3       전체  보훈대상자 평균 개인소득
..        ...     ...      ...            ...
97       근로소득  1814.9  보훈보상대상자  보훈대상자 평균 개인소득
98       사업소득   552.0  보훈보상대상자  보훈대상자 평균 개인소득
99       재산소득   126.1  보훈보상대상자  보훈대상자 평균 개인소득
100    사적이전소득    50.1  보훈보상대상자  보훈대상자 평균 개인소득
101    공적이전소득  1191.2  보훈보상대상자  보훈대상자 평균 개인소득

[102 rows x 4 columns]

In [6]:
# 인덱스 C1_NM으로 설정
df.set_index('C1_NM',inplace=True)

In [7]:
df

            C2_NM      DT         TBL_NM
C1_NM
전체       전체(경상소득)  2927.6  보훈대상자 평균 개인소득
전체           근로소득   789.0  보훈대상자 평균 개인소득
전체           사업소득   349.7  보훈대상자 평균 개인소득
전체           재산소득   142.2  보훈대상자 평균 개인소득
전체         사적이전소득    94.3  보훈대상자 평균 개인소득
...           ...     ...            ...
보훈보상대상자      근로소득  1814.9  보훈대상자 평균 개인소득
보훈보상대상자      사업소득   552.0  보훈대상자 평균 개인소득
보훈보상대상자      재산소득   126.1  보훈대상자 평균 개인소득
보훈보상대상자    사적이전소득    50.1  보훈대상자 평균 개인소득
보훈보상대상자    공적이전소득  1191.2  보훈대상자 평균 개인소득

[102 rows x 3 columns]

In [8]:
#인덱스 고유값 확인 
df.index.unique()

Index(['전체', '남성', '여성', '40대 이하', '50대', '60대', '70대', '80대 이상', '독립유공자',
       '국가유공자(본인)', '국가유공자(유족)', '5·18민주유공자', '참전유공자', '고엽제', '특수임무유공자',
       '제대군인', '보훈보상대상자'],
      dtype='object', name='C1_NM')

In [9]:
# 특정 인덱스 애들 꺼내서 데이터프레임을 만듦
man = ['국가유공자(본인)', '국가유공자(유족)', '고엽제', '참전유공자', '특수임무유공자']

dfs = df.loc[df.index.isin(man)]

In [10]:
dfs.index.unique()

Index(['국가유공자(본인)', '국가유공자(유족)', '참전유공자', '고엽제', '특수임무유공자'], dtype='object', name='C1_NM')

In [11]:
# 연도 컬럼 생성하기. 연도 옆에 row 수 만큼 곱해주면됌
연도 = [2021] * 30

In [12]:
dfs['연도'] = 연도

C:\Users\dino1\AppData\Local\Temp\ipykernel_24468\4164005312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs['연도'] = 연도

In [13]:
dfs

              C2_NM      DT         TBL_NM    연도
C1_NM
국가유공자(본인)  전체(경상소득)  3809.4  보훈대상자 평균 개인소득  2021
국가유공자(본인)      근로소득   929.3  보훈대상자 평균 개인소득  2021
국가유공자(본인)      사업소득   261.5  보훈대상자 평균 개인소득  2021
국가유공자(본인)      재산소득   126.8  보훈대상자 평균 개인소득  2021
국가유공자(본인)    사적이전소득    62.1  보훈대상자 평균 개인소득  2021
국가유공자(본인)    공적이전소득  2429.9  보훈대상자 평균 개인소득  2021
국가유공자(유족)  전체(경상소득)  2351.7  보훈대상자 평균 개인소득  2021
국가유공자(유족)      근로소득   538.0  보훈대상자 평균 개인소득  2021
국가유공자(유족)      사업소득   313.7  보훈대상자 평균 개인소득  2021
국가유공자(유족)      재산소득   120.6  보훈대상자 평균 개인소득  2021
국가유공자(유족)    사적이전소득   104.9  보훈대상자 평균 개인소득  2021
국가유공자(유족)    공적이전소득  1274.4  보훈대상자 평균 개인소득  2021
참전유공자      전체(경상소득)  2149.4  보훈대상자 평균 개인소득  2021
참전유공자          근로소득   233.6  보훈대상자 평균 개인소득  2021
참전유공자          사업소득   414.2  보훈대상자 평균 개인소득  2021
참전유공자          재산소득   196.9  보훈대상자 평균 개인소득  2021
참전유공자        사적이전소득   140.6  보훈대상자 평균 개인소득  2021
참전유공자        공적이전소득  1164.1  보훈대상자 평균 개인소득  2021
고엽제        전체(경상소득)  2188.8  보훈대상자 평균 개인소득  2021
고엽제            근로소득   202.8  보훈대상자 평균 개인소득  2021
고엽제            사업소득   162.4  보훈대상자 평균 개인소득  2021
고엽제            재산소득   165.3  보훈대상자 평균 개인소득  2021
고엽제          사적이전소득    94.7  보훈대상자 평균 개인소득  2021
고엽제          공적이전소득  1563.7  보훈대상자 평균 개인소득  2021
특수임무유공자    전체(경상소득)  3137.3  보훈대상자 평균 개인소득  2021
특수임무유공자        근로소득  1885.9  보훈대상자 평균 개인소득  2021
특수임무유공자        사업소득   634.3  보훈대상자 평균 개인소득  2021
특수임무유공자        재산소득    66.0  보훈대상자 평균 개인소득  2021
특수임무유공자      사적이전소득    82.5  보훈대상자 평균 개인소득  2021
특수임무유공자      공적이전소득   468.7  보훈대상자 평균 개인소득  2021

In [14]:
dfs = dfs.rename(columns={
    "C2_NM": "소득종류",
    "DT": "소득",
    "TBL_NM": "테이블명",
    "연도": "연도"
})
dfs.index.name = "구분"

dfs

               소득종류      소득           테이블명    연도
구분
국가유공자(본인)  전체(경상소득)  3809.4  보훈대상자 평균 개인소득  2021
국가유공자(본인)      근로소득   929.3  보훈대상자 평균 개인소득  2021
국가유공자(본인)      사업소득   261.5  보훈대상자 평균 개인소득  2021
국가유공자(본인)      재산소득   126.8  보훈대상자 평균 개인소득  2021
국가유공자(본인)    사적이전소득    62.1  보훈대상자 평균 개인소득  2021
국가유공자(본인)    공적이전소득  2429.9  보훈대상자 평균 개인소득  2021
국가유공자(유족)  전체(경상소득)  2351.7  보훈대상자 평균 개인소득  2021
국가유공자(유족)      근로소득   538.0  보훈대상자 평균 개인소득  2021
국가유공자(유족)      사업소득   313.7  보훈대상자 평균 개인소득  2021
국가유공자(유족)      재산소득   120.6  보훈대상자 평균 개인소득  2021
국가유공자(유족)    사적이전소득   104.9  보훈대상자 평균 개인소득  2021
국가유공자(유족)    공적이전소득  1274.4  보훈대상자 평균 개인소득  2021
참전유공자      전체(경상소득)  2149.4  보훈대상자 평균 개인소득  2021
참전유공자          근로소득   233.6  보훈대상자 평균 개인소득  2021
참전유공자          사업소득   414.2  보훈대상자 평균 개인소득  2021
참전유공자          재산소득   196.9  보훈대상자 평균 개인소득  2021
참전유공자        사적이전소득   140.6  보훈대상자 평균 개인소득  2021
참전유공자        공적이전소득  1164.1  보훈대상자 평균 개인소득  2021
고엽제        전체(경상소득)  2188.8  보훈대상자 평균 개인소득  2021
고엽제            근로소득   202.8  보훈대상자 평균 개인소득  2021
고엽제            사업소득   162.4  보훈대상자 평균 개인소득  2021
고엽제            재산소득   165.3  보훈대상자 평균 개인소득  2021
고엽제          사적이전소득    94.7  보훈대상자 평균 개인소득  2021
고엽제          공적이전소득  1563.7  보훈대상자 평균 개인소득  2021
특수임무유공자    전체(경상소득)  3137.3  보훈대상자 평균 개인소득  2021
특수임무유공자        근로소득  1885.9  보훈대상자 평균 개인소득  2021
특수임무유공자        사업소득   634.3  보훈대상자 평균 개인소득  2021
특수임무유공자        재산소득    66.0  보훈대상자 평균 개인소득  2021
특수임무유공자      사적이전소득    82.5  보훈대상자 평균 개인소득  2021
특수임무유공자      공적이전소득   468.7  보훈대상자 평균 개인소득  2021

In [15]:
dfs.to_csv('보훈대상자 평균 개인소득 2021 전처리.csv')