In [14]:
import pandas as pd
import io

# 업로드된 파일의 데이터
data = """통계표명:,1인당 국민총소득과 증가율,,,,,,,,,,
단위:,"만 원, %",,,,,,,,,,
,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
"1인당 실질 국민총소득(만 원)","3,459","3,666","3,820","3,932","3,992","4,003","4,004","4,161","4,147","4,228","4,391"
"전년 대비 증가율(%)",2.8,6.0,4.2,2.9,1.5,0.3,0.0,3.9,-0.3,1.9,3.9
"1인당 명목 국민총소득(만 원)","3,244","3,423","3,591","3,781","3,905","3,974","4,004","4,337","4,551","4,725","5,012"
"전년 대비 증가율(%)",3.5,5.5,4.9,5.3,3.3,1.8,0.7,8.3,4.9,3.8,6.1
출처:,"한국은행,「국민계정」, 통계청,「장래인구추계」",,,,,,,,,,
,"  * 자료 : 한국은행, 「국민계정」 각 연도, 통계청, 「장래인구추계(2022년 기준)」",,,,,,,,,,
주석:,1) 1인당 실질(명목) 국민총소득= 실질(명목) 국민총소득 ÷ 총인구.,,,,,,,,,,
,2) 명목 국민총소득은 명목 GDP에 명목 국외순수취요소소득을 더하여 산출함.,,,,,,,,,,
,3) 2020년 기준년 개편 국민계정 자료임.,,,,,,,,,,
,4) 2023년 이후는 잠정치임.,,,,,,,,,,
"""

# 텍스트 데이터를 DataFrame으로 읽기
# quotechar 매개변수를 사용하여 따옴표 처리를 명시적으로 지정
df = pd.read_csv(io.StringIO(data), header=2, quotechar='"')

# 불필요한 행과 열 제거
# '출처' 행과 '주석' 행을 제거
df = df.iloc[1:4, :]
df

,Unnamed: 0,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,전년 대비 증가율(%),2.8,6.0,4.2,2.9,1.5,0.3,0.0,3.9,-0.3,1.9,3.9
2,1인당 명목 국민총소득(만 원),"3,244","3,423","3,591","3,781","3,905","3,974","4,004","4,337","4,551","4,725","5,012"
3,전년 대비 증가율(%),3.5,5.5,4.9,5.3,3.3,1.8,0.7,8.3,4.9,3.8,6.1

In [16]:
# 칼럼 이름 정리
df.columns = ['지표', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
df

,지표,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,전년 대비 증가율(%),2.8,6.0,4.2,2.9,1.5,0.3,0.0,3.9,-0.3,1.9,3.9
2,1인당 명목 국민총소득(만 원),"3,244","3,423","3,591","3,781","3,905","3,974","4,004","4,337","4,551","4,725","5,012"
3,전년 대비 증가율(%),3.5,5.5,4.9,5.3,3.3,1.8,0.7,8.3,4.9,3.8,6.1

In [17]:
# 행과 열을 바꾸어 피벗
df = df.set_index('지표').T
df

지표   전년 대비 증가율(%) 1인당 명목 국민총소득(만 원) 전년 대비 증가율(%)
2014          2.8             3,244          3.5
2015          6.0             3,423          5.5
2016          4.2             3,591          4.9
2017          2.9             3,781          5.3
2018          1.5             3,905          3.3
2019          0.3             3,974          1.8
2020          0.0             4,004          0.7
2021          3.9             4,337          8.3
2022         -0.3             4,551          4.9
2023          1.9             4,725          3.8
2024          3.9             5,012          6.1

In [18]:
# 칼럼 이름 변경
df.columns = ['전년 대비 증가율(실질)(%)','1인당 실질 국민총소득(만 원)', '전년 대비 증가율(명목)(%)']
df.index.name = '연도'
df

     전년 대비 증가율(실질)(%) 1인당 실질 국민총소득(만 원) 전년 대비 증가율(명목)(%)
연도
2014              2.8             3,244              3.5
2015              6.0             3,423              5.5
2016              4.2             3,591              4.9
2017              2.9             3,781              5.3
2018              1.5             3,905              3.3
2019              0.3             3,974              1.8
2020              0.0             4,004              0.7
2021              3.9             4,337              8.3
2022             -0.3             4,551              4.9
2023              1.9             4,725              3.8
2024              3.9             5,012              6.1

In [21]:
# CSV 파일로 저장
df.to_csv('국민총소득.csv', encoding='utf-8-sig',index=False)
print(df.to_csv())

연도,전년 대비 증가율(실질)(%),1인당 실질 국민총소득(만 원),전년 대비 증가율(명목)(%)
2014,2.8,"3,244",3.5
2015,6.0,"3,423",5.5
2016,4.2,"3,591",4.9
2017,2.9,"3,781",5.3
2018,1.5,"3,905",3.3
2019,0.3,"3,974",1.8
2020,0.0,"4,004",0.7
2021,3.9,"4,337",8.3
2022,-0.3,"4,551",4.9
2023,1.9,"4,725",3.8
2024,3.9,"5,012",6.1