In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv('train (2).csv')
train_df

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58640,58640,34,120000,MORTGAGE,5.0,EDUCATION,D,25000,15.95,0.21,Y,10,0
58641,58641,28,28800,RENT,0.0,MEDICAL,C,10000,12.73,0.35,N,8,1
58642,58642,23,44000,RENT,7.0,EDUCATION,D,6800,16.00,0.15,N,2,1
58643,58643,22,30000,RENT,2.0,EDUCATION,A,5000,8.90,0.17,N,3,0
58644,58644,31,75000,MORTGAGE,2.0,VENTURE,B,15000,11.11,0.20,N,5,0

id : 고유 식별자    
person_age : 신청자의 나이  
person_income : 연간 소득   
person_home_ownership : 주거 형태       
person_emp_length : 고용 기간   
loan_intent : 대출 목적   
loan_grade : 신용 등급     
loan_amnt : 대출 신청 금액    
loan_int_rate : 대출 이자율       
loan_percent_income : 대출금이 소득에서 차지하는 비율     
cb_person_default_on_file : 과거 채무불이행 이력 여부     
cb_person_cred_hist_length : 신용기록 유지 기간       
loan_status : 대출 상환 여부(타겟 피처)

In [3]:
train_df.describe()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status
count,58645.000000,58645.000000,5.864500e+04,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000
mean,29322.000000,27.550857,6.404617e+04,4.701015,9217.556518,10.677874,0.159238,5.813556,0.142382
std,16929.497605,6.033216,3.793111e+04,3.959784,5563.807384,3.034697,0.091692,4.029196,0.349445
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,0.000000
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000
max,58644.000000,123.000000,1.900000e+06,123.000000,35000.000000,23.220000,0.830000,30.000000,1.000000

In [4]:
train_df['person_home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER'], dtype=object)

In [5]:
train_df['loan_intent'].unique()

array(['EDUCATION', 'MEDICAL', 'PERSONAL', 'VENTURE', 'DEBTCONSOLIDATION',
       'HOMEIMPROVEMENT'], dtype=object)

In [6]:
train_df.isna().sum()

id                            0
person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
loan_status                   0
dtype: int64

In [7]:
train_df.dtypes

id                              int64
person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
loan_status                     int64
dtype: object

In [9]:
train_df['loan_intent'] = train_df['loan_intent'].map({
    'EDUCATION' : 1,
    'MEDICAL'   : 2,
    'PERSONAL'  : 3,
    'VENTURE'   : 4,
    'DEBTCONSOLIDATION'   : 5,
    'HOMEIMPROVEMENT'     : 6
})

In [ ]:
ohe_df = pd.get_dummies(train_df, columns = ['cb_person_default_on_file'],drop_first=True)

In [12]:
ohe_df['loan_grade'] = ohe_df['loan_grade'].map({
    'A' : 7,
    'B' : 6,
    'C' : 5,
    'D' : 4,
    'E' : 3,
    'F' : 2,
    'G' : 1
})

In [13]:
ohe_df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status,cb_person_default_on_file_N,cb_person_default_on_file_Y
0,0,37,35000,RENT,0.0,1,6,6000,11.49,0.17,14,0,True,False
1,1,22,56000,OWN,6.0,2,5,4000,13.35,0.07,2,0,True,False
2,2,29,28800,OWN,8.0,3,7,6000,8.90,0.21,10,0,True,False
3,3,30,70000,RENT,14.0,4,6,12000,11.11,0.17,5,0,True,False
4,4,22,60000,RENT,2.0,2,7,6000,6.92,0.10,3,0,True,False

In [14]:
ohe_df2 = pd.get_dummies(ohe_df,columns = ['person_home_ownership'])

In [15]:
ohe_df2.dtypes

id                                  int64
person_age                          int64
person_income                       int64
person_emp_length                 float64
loan_intent                         int64
loan_grade                          int64
loan_amnt                           int64
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length          int64
loan_status                         int64
cb_person_default_on_file_N          bool
cb_person_default_on_file_Y          bool
person_home_ownership_MORTGAGE       bool
person_home_ownership_OTHER          bool
person_home_ownership_OWN            bool
person_home_ownership_RENT           bool
dtype: object

In [16]:
X = ohe_df2.drop(columns=['id','loan_status'])
y = ohe_df2['loan_status']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=2020158011)

In [ ]:
from lazypredict.Supervised import LazyRegressor

reg = LazyRegressor(verbose=0)
models, prediction = reg.fit(X_train,X_val,y_train,y_val)

  0%|          | 0/42 [00:00<?, ?it/s]