In [3]:
import pandas as pd

df = pd.read_csv('보훈대상자 평균 개인소득 총집합.csv')
df

           구분      소득종류      소득           테이블명    연도
0   국가유공자(본인)  전체(경상소득)  4253.0  보훈대상자 평균 개인소득  2018
1   국가유공자(본인)      근로소득  1634.0  보훈대상자 평균 개인소득  2018
2   국가유공자(본인)      사업소득   484.0  보훈대상자 평균 개인소득  2018
3   국가유공자(본인)      재산소득   164.0  보훈대상자 평균 개인소득  2018
4   국가유공자(본인)    사적이전소득    57.0  보훈대상자 평균 개인소득  2018
..        ...       ...     ...            ...   ...
85    특수임무유공자      근로소득  1861.0  보훈대상자 평균 개인소득  2024
86    특수임무유공자      사업소득   489.0  보훈대상자 평균 개인소득  2024
87    특수임무유공자      재산소득    79.0  보훈대상자 평균 개인소득  2024
88    특수임무유공자    사적이전소득    95.0  보훈대상자 평균 개인소득  2024
89    특수임무유공자    공적이전소득   424.0  보훈대상자 평균 개인소득  2024

[90 rows x 5 columns]

In [6]:
# 컬럼 명 변경
df = df.rename(columns={'소득': '연간 소득'})

In [10]:
# 경상소득 데이터만 추출
dfs = df[df['소득종류'] == '전체(경상소득)']
dfs.head()

           구분      소득종류   연간 소득           테이블명    연도
0   국가유공자(본인)  전체(경상소득)  4253.0  보훈대상자 평균 개인소득  2018
6   국가유공자(유족)  전체(경상소득)  2026.0  보훈대상자 평균 개인소득  2018
12      참전유공자  전체(경상소득)  1838.0  보훈대상자 평균 개인소득  2018
18        고엽제  전체(경상소득)  2301.0  보훈대상자 평균 개인소득  2018
24    특수임무유공자  전체(경상소득)  3274.0  보훈대상자 평균 개인소득  2018

In [23]:
# 경상소득 데이터 복사
dfs = df[df['소득종류'] == '전체(경상소득)'].copy()
dfs

           구분      소득종류   연간 소득           테이블명    연도
0   국가유공자(본인)  전체(경상소득)  4253.0  보훈대상자 평균 개인소득  2018
6   국가유공자(유족)  전체(경상소득)  2026.0  보훈대상자 평균 개인소득  2018
12      참전유공자  전체(경상소득)  1838.0  보훈대상자 평균 개인소득  2018
18        고엽제  전체(경상소득)  2301.0  보훈대상자 평균 개인소득  2018
24    특수임무유공자  전체(경상소득)  3274.0  보훈대상자 평균 개인소득  2018
30  국가유공자(본인)  전체(경상소득)  3809.4  보훈대상자 평균 개인소득  2021
36  국가유공자(유족)  전체(경상소득)  2351.7  보훈대상자 평균 개인소득  2021
42      참전유공자  전체(경상소득)  2149.4  보훈대상자 평균 개인소득  2021
48        고엽제  전체(경상소득)  2188.8  보훈대상자 평균 개인소득  2021
54    특수임무유공자  전체(경상소득)  3137.3  보훈대상자 평균 개인소득  2021
60  국가유공자(본인)  전체(경상소득)  3884.0  보훈대상자 평균 개인소득  2024
66  국가유공자(유족)  전체(경상소득)  2441.0  보훈대상자 평균 개인소득  2024
72      참전유공자  전체(경상소득)  2055.0  보훈대상자 평균 개인소득  2024
78        고엽제  전체(경상소득)  2422.0  보훈대상자 평균 개인소득  2024
84    특수임무유공자  전체(경상소득)  2948.0  보훈대상자 평균 개인소득  2024

In [27]:
# 월간 소득 컬럼 생성 후 반올림
dfs['월간 소득'] = round(dfs['연간 소득'] / 12.0,1)
dfs

           구분      소득종류   연간 소득           테이블명    연도  월간 소득
0   국가유공자(본인)  전체(경상소득)  4253.0  보훈대상자 평균 개인소득  2018  354.4
6   국가유공자(유족)  전체(경상소득)  2026.0  보훈대상자 평균 개인소득  2018  168.8
12      참전유공자  전체(경상소득)  1838.0  보훈대상자 평균 개인소득  2018  153.2
18        고엽제  전체(경상소득)  2301.0  보훈대상자 평균 개인소득  2018  191.8
24    특수임무유공자  전체(경상소득)  3274.0  보훈대상자 평균 개인소득  2018  272.8
30  국가유공자(본인)  전체(경상소득)  3809.4  보훈대상자 평균 개인소득  2021  317.4
36  국가유공자(유족)  전체(경상소득)  2351.7  보훈대상자 평균 개인소득  2021  196.0
42      참전유공자  전체(경상소득)  2149.4  보훈대상자 평균 개인소득  2021  179.1
48        고엽제  전체(경상소득)  2188.8  보훈대상자 평균 개인소득  2021  182.4
54    특수임무유공자  전체(경상소득)  3137.3  보훈대상자 평균 개인소득  2021  261.4
60  국가유공자(본인)  전체(경상소득)  3884.0  보훈대상자 평균 개인소득  2024  323.7
66  국가유공자(유족)  전체(경상소득)  2441.0  보훈대상자 평균 개인소득  2024  203.4
72      참전유공자  전체(경상소득)  2055.0  보훈대상자 평균 개인소득  2024  171.2
78        고엽제  전체(경상소득)  2422.0  보훈대상자 평균 개인소득  2024  201.8
84    특수임무유공자  전체(경상소득)  2948.0  보훈대상자 평균 개인소득  2024  245.7

In [28]:
csv 파일로 저장
dfs.to_csv('보훈대상자 평균 개인소득 총집합(월간 소득 컬럼 추가).csv',index=False)

In [29]:
dfs

           구분      소득종류   연간 소득           테이블명    연도  월간 소득
0   국가유공자(본인)  전체(경상소득)  4253.0  보훈대상자 평균 개인소득  2018  354.4
6   국가유공자(유족)  전체(경상소득)  2026.0  보훈대상자 평균 개인소득  2018  168.8
12      참전유공자  전체(경상소득)  1838.0  보훈대상자 평균 개인소득  2018  153.2
18        고엽제  전체(경상소득)  2301.0  보훈대상자 평균 개인소득  2018  191.8
24    특수임무유공자  전체(경상소득)  3274.0  보훈대상자 평균 개인소득  2018  272.8
30  국가유공자(본인)  전체(경상소득)  3809.4  보훈대상자 평균 개인소득  2021  317.4
36  국가유공자(유족)  전체(경상소득)  2351.7  보훈대상자 평균 개인소득  2021  196.0
42      참전유공자  전체(경상소득)  2149.4  보훈대상자 평균 개인소득  2021  179.1
48        고엽제  전체(경상소득)  2188.8  보훈대상자 평균 개인소득  2021  182.4
54    특수임무유공자  전체(경상소득)  3137.3  보훈대상자 평균 개인소득  2021  261.4
60  국가유공자(본인)  전체(경상소득)  3884.0  보훈대상자 평균 개인소득  2024  323.7
66  국가유공자(유족)  전체(경상소득)  2441.0  보훈대상자 평균 개인소득  2024  203.4
72      참전유공자  전체(경상소득)  2055.0  보훈대상자 평균 개인소득  2024  171.2
78        고엽제  전체(경상소득)  2422.0  보훈대상자 평균 개인소득  2024  201.8
84    특수임무유공자  전체(경상소득)  2948.0  보훈대상자 평균 개인소득  2024  245.7

In [ ]:
pd.read_csv('보훈대상자 평균 개인소득 총집합(월간 소득 컬럼 추가).csv')